name: python 3.10
channels:
  - conda-forge
dependencies:
  - python=3.10 
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - seaborn
  - scikit-learn
  - nbformat
  - prophet
